# Generated by Django 6.0.5 on 2026-07-18 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('staff', 'Staff')], default='staff', help_text='User role: Admin has full access, Staff has limited access', max_length=10),
        ),
    ]
